-- Create table to track used QR codes
CREATE TABLE public.used_qr_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qr_token TEXT NOT NULL UNIQUE,
  customer_id UUID NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  amount_spent DECIMAL(10,2) NOT NULL,
  points_awarded INTEGER NOT NULL
);

-- Enable RLS
ALTER TABLE public.used_qr_codes ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Used QR codes are readable by system" 
ON public.used_qr_codes 
FOR SELECT 
USING (true);

-- Create index for performance
CREATE INDEX idx_used_qr_codes_token ON public.used_qr_codes(qr_token);
CREATE INDEX idx_used_qr_codes_customer ON public.used_qr_codes(customer_id);